// Mock analysis data — Python code, line-by-line risk scoring
// Each line: { code, score (0-100), tags, advice }

window.CRASH_DATA = {
  language: "Python",
  filename: "data_pipeline.py",
  summary: {
    riskScore: 67,
    linesScanned: 42,
    hotspots: 8,
    estComplexity: "O(n²)",
    issues: { critical: 2, warning: 4, info: 5 },
  },
  lines: [
    { code: "import json", score: 4 },
    { code: "import requests", score: 6 },
    { code: "from collections import defaultdict", score: 5 },
    { code: "", score: 0 },
    { code: "# Fetch users and aggregate their orders", score: 8 },
    { code: "def aggregate_user_orders(user_ids):", score: 22, advice: "함수 시그니처가 단일 책임을 넘어서고 있습니다. fetch / aggregate 분리를 고려하세요." },
    { code: "    results = {}", score: 12 },
    { code: "    for uid in user_ids:", score: 28, advice: "외부 루프 진입점. 안쪽에서 O(n) 네트워크 호출이 발생하면 전체가 O(n²)에 가까워집니다." },
    { code: "        res = requests.get(f\"https://api.shop/users/{uid}\")", score: 86, tags: ["network", "blocking"], advice: "N+1 패턴. user_id 마다 동기 HTTP 호출을 발생시킵니다. 배치 엔드포인트 또는 asyncio.gather 로 병렬화하세요." },
    { code: "        if res.status_code != 200:", score: 31, advice: "상태 코드만 체크합니다. 408/429/5xx 별 재시도 전략이 없습니다." },
    { code: "            continue", score: 18 },
    { code: "        user = res.json()", score: 24 },
    { code: "        orders = []", score: 9 },
    { code: "        for oid in user[\"order_ids\"]:", score: 64, advice: "중첩 루프. user 당 order_id 마다 또 한 번의 요청이 발생합니다." },
    { code: "            o = requests.get(f\"https://api.shop/orders/{oid}\").json()", score: 94, tags: ["network", "no-timeout", "no-error-handling"], advice: "치명적: 타임아웃 없음, 에러 처리 없음, N×M 네트워크 호출. 가장 큰 병목입니다." },
    { code: "            orders.append(o)", score: 14 },
    { code: "        total = 0", score: 8 },
    { code: "        for o in orders:", score: 22 },
    { code: "            for item in o[\"items\"]:", score: 38, advice: "3중 중첩 루프 진입. items 합계는 sum(item['price'] for ...) 한 줄로 줄일 수 있습니다." },
    { code: "                total += item[\"price\"] * item[\"qty\"]", score: 27 },
    { code: "        results[uid] = {", score: 11 },
    { code: "            \"name\": user[\"name\"],", score: 7 },
    { code: "            \"orders\": orders,", score: 10 },
    { code: "            \"total\": total,", score: 6 },
    { code: "        }", score: 4 },
    { code: "    return results", score: 8 },
    { code: "", score: 0 },
    { code: "# Find duplicate emails across all users", score: 9 },
    { code: "def find_duplicate_emails(users):", score: 16 },
    { code: "    duplicates = []", score: 7 },
    { code: "    for i in range(len(users)):", score: 42, advice: "O(n²) 의도. set() 으로 O(n)에 풀 수 있습니다." },
    { code: "        for j in range(i + 1, len(users)):", score: 71, tags: ["O(n²)"], advice: "이중 루프 비교. 100k 유저에서 1만 배 느려집니다." },
    { code: "            if users[i][\"email\"] == users[j][\"email\"]:", score: 58 },
    { code: "                if users[i][\"email\"] not in duplicates:", score: 49, advice: "list 멤버십 검사는 O(n). duplicates 를 set 으로 바꾸면 O(1)." },
    { code: "                    duplicates.append(users[i][\"email\"])", score: 32 },
    { code: "    return duplicates", score: 11 },
    { code: "", score: 0 },
    { code: "# Entry point", score: 5 },
    { code: "if __name__ == \"__main__\":", score: 7 },
    { code: "    ids = json.load(open(\"users.json\"))", score: 54, tags: ["resource-leak"], advice: "파일 핸들이 닫히지 않습니다. `with open(...) as f:` 패턴을 사용하세요." },
    { code: "    data = aggregate_user_orders(ids)", score: 19 },
    { code: "    print(json.dumps(data, indent=2))", score: 8 },
  ],
};
